### DISCUSSION TITLE
`check_model_has_meta_keys` check doesn't work with meta keys with a list of values

### DISCUSSION THREAD

**Discussion by LoekBotman** [godatadriven/dbt-bouncer#344] [General]
Hi! I'm considering using the dbt-bouncer package in our dbt project to enforce our dbt conventions and I really like it so far. I just ran into one issue that seems to be a bug in the `check_model_has_meta_keys` check. 

If I add the following meta data to my dbt model:
```
meta:
  key_1: abc
  key_2:
    - a
    - b
    - c
```

And I define my dbt-bouncer check like this:

```
- name: check_model_has_meta_keys
  include: ^models/entities
  keys:
    - key_1
    - key_2
```

I get an error saying that my model is missing the key `key_2`.
<img width="1050" alt="image" src="https://github.com/user-attachments/assets/bdb6bb40-f8d3-441b-8ea0-79ce9d28db21" />

I expect that it's related to row 82 in the `src/dbt_bouncer/utils.py` file in (the function `find_missing_meta_keys`).

I wonder if it's indeed a bug or if there's a reason why it should fail. And if it's a bug, is it something you can fix in a later version?
