### ISSUE TITLE
[Bug] check-model-directories check ignores first character of path

### ISSUE THREAD

**Issue by Thootje** [godatadriven/dbt-bouncer#351]
### Current Behavior

When doing a `check_model_directories` check, dbt-bouncer seems to ignore the first character of the permitted_sub_directory paths when including a trailing `/` for the `include: models/domains/` config. The check therefore fails.

```
manifest_checks:

  #Model check
  - name: check_model_directories
    include: models/domains/
    permitted_sub_directories:
      - product_development_and_pricing
      - procurement_and_sourcing
      - planning_and_forecasting
      - supply_chain_and_logistics
      - sales_and_marketing
      - finance_legal_and_sustainability
      - people
      - business_technology
```

![Image](https://github.com/user-attachments/assets/6e5db6f5-1263-4c39-aebe-3a584d46d34b)

### Expected Behavior

`dbt-bouncer` should nicely account for trailing `/`. 

### Steps To Reproduce

1. Use this config (and add the corresponding directories in your project structure). Be sure to include the trailing `/`:
```
manifest_checks:
  - name: check_model_directories
    include: models/
    permitted_sub_directories:
      - staging
      - intermediate
      - mart

```
2. Run `dbt-bouncer`

### Relevant log output

```shell

```

### Environment

```markdown
- OS: OSX Sequoia 15.4.1
- Python: 3.12.8
- dbt-bouncer: 1.11.0
```
